### PR TITLE
#64 update id commit message

### PR DESCRIPTION
**Pull request by BernardJeremy**
#64 fix

### CODE REVIEW

**Comment by Grenadingue** [comment]
Are we sure that all the commits needed are in this PR ?
Are we sure that there will be no conflicts during the merge ? How ?

**Comment by BernardJeremy** [comment]
_ALL_ project's commit are in this PR. I woold think that it's enough

There will be no conflict, simply because only commit's message are updated.

**Comment by Grenadingue** [comment]
From this PR:

```
#HS-0: fix next to merge - 982df29
#HS-00: merge with develop - a8efe01
Merge pull request #44 from EIP-SAM/module_log … - b76e13f
```

From develop:

```
#0: fix next to merge - f622928
#00: merge with develop - a96c5ae
Merge pull request #44 from EIP-SAM/module_log … - 01e44c5
```

You can see that the commit ids had changed. How can we know that the previous ones will be deleted, then replaced by the new ones, and then that the next commits (in develop) following those will be append to the whole thing?
A copy/paste of the command you used might be the only needed thing to explain everything.

**Comment by BernardJeremy** [comment]
`git filter-branch --msg-filter 'sed -e "s/^#/#HS-/"'`

But indeed, since we wait too long to merge this PR, some conflict showed up.
I close without mergin for now, the id issue is not as problematic as I thought.

**Pull request closed without merging**
